### ISSUE TITLE
Browser freezes when using setHtml on Reader innerContainer

### ISSUE THREAD

**Issue by ajmacdonald** [sgsinclair/Voyant#109]
This commit added an extra div which gets replaced on update which solves the issue: https://github.com/sgsinclair/Voyant/commit/61bef648d3c251b76e650253a8ff53f70c85ed3c
However this might be worth returning to.

**Comment by sgsinclair** [comment]
Is this worth returning to @ajmacdonald?

**Comment by ajmacdonald** [comment]
I think this can be closed.
