### ISSUE TITLE
Upgrade to Jetty 9 (prior versions are now EOL)

### ISSUE THREAD

**Issue by joakime** [sgsinclair/Voyant#151]
You have several old reference to Jetty 6 ...

eg:
```
     <plugin>
        <groupId>org.mortbay.jetty</groupId>
        <artifactId>maven-jetty-plugin</artifactId>
      </plugin>
```

and even Jetty 7.

Jetty 6 was EOL (End of Life) back in 2010.
Jetty 7 was EOL in 2014.

**Comment by sgsinclair** [comment]
Thanks! I'm not entirely sure this does it, but please reopen the ticket if not.

cbe0e59d924fd753362b25fbff7cd83a58c19005

**Comment by joakime** [comment]
might want to tack a `<version>` on there.
