### ISSUE TITLE
undefined is not a function whent trying to export grid data to json/html/csv

### ISSUE THREAD

**Issue by philstel** [sgsinclair/Voyant#158]
I'm getting an "Uncaught TypeError: undefined is not a function", when trying to export data from the "CorpusTerms" Panel in format json, html and csv.

The error seems to be in "exportGridCurrentJson" in file "Toolable.js", line 429.
The grid.getStore() method seems to return a not fully initialized store? The "each" and other methods (e.g. "first()") don't seem to exist

My extjs knowledge is not good enough to make a pull request myself.

**Comment by sgsinclair** [comment]
Thanks very much Phil!

1405884a5376cc36b26995dc3674a79195b46720
