### ISSUE TITLE
Knots implemented in V2

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#221]

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/Voyant/commit/91a57d5f537010c1036d327fecadd51196b4dfd4
https://github.com/sgsinclair/Voyant/commit/c57f3cf212a6ba26e5b483e83a42ee4e0768b082
https://github.com/sgsinclair/Voyant/commit/8b37a6d8877ccca02f758b4a16b2004763853a4c
