### ISSUE TITLE
Wordtrends can support streamgraph

### ISSUE THREAD

**Issue by ip1200** [sgsinclair/Voyant#227]
I find the streamgraph is very interesting, and indeed makes sense. Thus I have a dream that you can add it to the Trends Tool. I googled and find there is no tool that can generate a streamgraph online with the data given by the user friendly. (R can, but too complex for a beginner)
If interested in, you may find some useful code on Github (e.g. https://github.com/leebyron/streamgraph) under the BSD licensen and someting else on http://bl.ocks.org/mbostock/4060954

**Comment by sgsinclair** [comment]
@ajmacdonald anything to do here before we close?

**Comment by ajmacdonald** [comment]
@sgsinclair No I don't think so.

**Comment by sgsinclair** [comment]
will be included in V2 M10
