### ISSUE TITLE
Terms Radio doesn't show trend lines for some texts

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#230]
Noticed while working on [this Chinese text](https://github.com/sgsinclair/Voyant/files/44629/1954.txt) (from #224). Characters appear properly, but the trend lines don't.

![terms radio no trend lines](https://cloud.githubusercontent.com/assets/355388/11474119/1167c5ea-9744-11e5-8b25-8789ebc09263.png)

**Comment by ip1200** [comment]
hope to sovle this little bug~

**Comment by ajmacdonald** [comment]
@sgsinclair All the characters are getting filtered out here: https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/app/panel/TermsRadio.js#L2180 
If I comment out that line it seems to work, but I'm wondering if that will mess up something else?

**Comment by sgsinclair** [comment]
Let's try it with no filtering (just return the passed string) and we'll see if other bugs appear.

**Comment by ip1200** [comment]
nice work！
