### ISSUE TITLE
Implement word tree

### ISSUE THREAD

**Issue by ajmacdonald** [sgsinclair/Voyant#233]
https://www.jasondavies.com/wordtree/

**Comment by ip1200** [comment]
looking forward

**Comment by sgsinclair** [comment]
updates @ajmacdonald?

**Comment by ajmacdonald** [comment]
No recent updates on this tool. I believe all major functionality is in place.

**Comment by ajmacdonald** [comment]
There are a few improvements I'm currently working on for this.

**Comment by sgsinclair** [comment]
@ajmacdonald can you create new issues for any remaining items you wanted to do for this? In the meantime I'll close this ticket since we now have a working word tree.
