### ISSUE TITLE
helping for internationalization

### ISSUE THREAD

**Issue by emchateau** [sgsinclair/Voyant#296]
Hi @sgsinclair, I may help for internationalization
Seems we should change this file https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/resources/voyant/current/voyant-locale-fr.js

Do you have any exemple of the result you want ? I suppose we should only translate de second part of the key value, is there any way to keep the english version close to it ?

Best regards, 
Emmanuel

**Comment by sgsinclair** [comment]
Bonjour Emmanuel! En fait, le fichier dont tu parles est généré à partir d'un tableur avec toutes les langues (c'est simple mais assez efficace comme système): https://docs.google.com/spreadsheets/d/1uOk-g8weVnBTSIUrM5PC-Fg6b6__SJlvN6BXPZvMrQs/edit?usp=sharing

Je t'inviterai à éditer le fichier.
