### ISSUE TITLE
VT sous Mac

### ISSUE THREAD

**Issue by spouyllau** [sgsinclair/Voyant#310]
Bonjour Stefan,
J'ai un bug au lancement de VT sous Mac :

Dans la console de VT :

> *** Starting Voyant Server – Web page will open automatically when ready ***
> 
> Using Free AdminPort=34000
> Server Starting
> 2016-07-08 11:46:07.282:INFO::main: Logging initialized @119ms
> Jetty Version: 9.2.z-SNAPSHOT
> http://*:8888
> Jetty starting up ... please wait
> 2016-07-08 11:46:07.363:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
> 2016-07-08 11:46:07.862:WARN:oejs.SecurityHandler:main: ServletContext@o.e.j.w.WebAppContext@4e04a765{/,file:/Users/stephanepouyllau/Downloads/VoyantServer2_0/_app/,STARTING} has uncovered http methods for path: /
> 2016-07-08 11:46:08.054:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4e04a765{/,file:/Users/stephanepouyllau/Downloads/VoyantServer2_0/_app/,AVAILABLE}
> 2016-07-08 11:46:08.081:INFO:oejs.ServerConnector:main: Started ServerConnector@16f7c8c1{HTTP/1.1}{0.0.0.0:8888}
> 2016-07-08 11:46:08.081:INFO:oejs.Server:main: Started @958ms
> ... Jetty has started.
> ERROR: Compilation error
> org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
> 	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
> 	at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:367)
> 	at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:324)
> 	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:102)
> 	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
> 	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
> 	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:168)
> 	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:2376)
> 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1004)
> 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1219)
> 	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:528)
> 	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:759)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:464)
> 	at org.apache.jasper.compiler.JDTJavaCompiler.compile(JDTJavaCompiler.java:503)
> 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:368)
> 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
> 	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
> 	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:485)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
> 	at java.lang.Thread.run(Thread.java:745)
> ERROR: Error compiling file: /Users/stephanepouyllau/Downloads/VoyantServer2_0/data/jetty-0.0.0.0-8888-_app-_-any-7428378260220801016.dir/jsp/org/apache/jsp/index_jsp.java
> 2016-07-08 11:46:08.796:WARN:oejs.ServletHandler:qtp321001045-15: 
> org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP||PWC6199: Generated servlet error:|The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files||
> 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
> 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
> 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
> 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
> 	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
> 	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:485)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
> 	at java.lang.Thread.run(Thread.java:745)
>

Sur la page web :

> HTTP ERROR 500
> 
> Problem accessing /. Reason:
> 
>     Server Error
> Caused by:
> 
> org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP
> 
> PWC6199: Generated servlet error:
> The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files
> 
> 
> 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
> 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
> 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
> 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
> 	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
> 	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:485)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
> 	at java.lang.Thread.run(Thread.java:745)
> Powered by Jetty://

Environnement : 
* Mac OS X El Capitan
* Java 8 maj 92

Cordialement,
Stéphane.

**Comment by sgsinclair** [comment]
La version 2.0 a effectivement des problèmes de compatibilité, essayez pour l'instant la version 2.1 M5 (2.1 tout court devrait paraître d'ici quelques jours) : https://github.com/sgsinclair/VoyantServer/releases/tag/2.1.0-M5
