### ISSUE TITLE
support for ssl

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#314]
It'll be up to individual instances to take care of certs, but a few tweaks will be needed to ensure that Voyant is SSL ready, especially in avoiding mixed content.

**Comment by sgsinclair** [comment]
28adb5b378a10f1dd8dafb5299a3cc839727b442

**Comment by pguerr061703** [comment]
Hi.
Can you help me identify the tweaks for Voyant to be SSL ready? 
When I run Voyant on a virtual server connected to a Netscalar( router), I get a spinning owl from the URL (cname). When I run voyant and point directly to the server name, it works fine.
Appears to be mixed content issue within Voyant (but I don't know how to fix it ). 
Any help would be greatly appreciated.

**Comment by sgsinclair** [comment]
duplicate of https://github.com/sgsinclair/VoyantServer/issues/15
