### ISSUE TITLE
Cirrus (svg) has trouble displaying small number of terms

### ISSUE THREAD

**Issue by ajmacdonald** [sgsinclair/Voyant#319]
`[{term:"foo",rawFreq:10},{term:"bar",rawFreq:15},{term:"baz",rawFreq:20}]` only display two terms.
Sizing algorithms need work.

**Comment by sgsinclair** [comment]
related? https://github.com/jasondavies/d3-cloud/issues/36

**Comment by ajmacdonald** [comment]
Yes I think so. In my test it was the largest word that was excluded.

**Comment by sgsinclair** [comment]
Where is this one at @ajmacdonald?

**Comment by ajmacdonald** [comment]
The referenced d3-cloud issue hasn't been resolved. I can try to implement some of the suggested solutions on that page however.

**Comment by sgsinclair** [comment]
So @ajmacdonald can we close this?

**Comment by ajmacdonald** [comment]
I think so.
