### ISSUE TITLE
Use Voyant with Nginx and forward to SSL

### ISSUE THREAD

**Issue by pguerr061703** [sgsinclair/Voyant#335]
Can someone please assist,
I have VoyantServer2_2M2 running manually on Redhat 6 via running command
java - jar /opt/VoyantServer2/VoyantServer.jar  --headless=true &

I want my VoyantServer URL (voyant.ace.fordham.edu)  to go from http-->https
I created a self-signed SSL certificate via http://www.akadia.com/services/ssh_test_certificate.html

Can someone please let me know if this is the correct setup for Nginx
I installed nginx 1.10.3...but not familiar with the setup.
[root@ace-linux29 sites-enabled]# rpm -qa | grep nginx
nginx-1.10.3-1.el6.ngx.x86_64
[root@ace-linux29 sites-enabled]#

Link
https://hub.docker.com/r/sepastian/voyant-docker/
Voyant behind Nginx
Next is an example configuration of Nginx to forward requests to your.server.com/voyant to http://localhost:8080/voyant. This may come in handy if you want to serve Voyant tools to a broader public, on port 80 (HTTP) instead of port 8080 (which may be blocked by your firewall).

Note: the path /voyant cannot be changed, because Tomcat has been configured to serve the Voyant app there. You are free to substitute any valid URL for your.server.com.

# /etc/nginx/sites-enabled/default, normally a symlink to /etc/nginx/sites-available/default
server {
    listen 80;
    server_name your.server.com;
    location /voyant {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8080/voyant;

**Comment by sgsinclair** [comment]
https://github.com/sgsinclair/Voyant/issues/331#issuecomment-276152834
