### ISSUE TITLE
access management issue: cannot access full text even with correct password

### ISSUE THREAD

**Issue by mysheepb** [sgsinclair/Voyant#336]
After uploading text with the access management option set, tools like Context and Reader show "This is a limited access corpus and this tool's functionality is restricted." which is expected. But even when the correct access password is entered, the same message blocks the tools. I have tried both the admin code and the access code, the issue is still there. I suppose when someone entered the correct code, tools like Context and Reader should function normally, but it is not the case now.

**Comment by mysheepb** [comment]
Am I not raising this issue in the right place? Or is there something wrong with my way of describing the issue? Please let me know. Thanks a lot!

**Comment by sgsinclair** [comment]
Your report is good, thanks, this is next on my list (and perhaps one of the last issues before we release 2.2!)

**Comment by mysheepb** [comment]
Thanks so much!

**Comment by sgsinclair** [comment]
This should now be fixed. It's not available on the standalone (2.2M4) but I did do a hot deploy so that the currently hosted version would work properly. Please test and let me know!

a1eae836c4500364aecde21e46255678ced7a41c
