### ISSUE TITLE
support for ssl

### ISSUE THREAD

**Issue by pguerr061703** [sgsinclair/Voyant#337]
Can you let me know what specific tweaks are needed for Voyant to support SSL.
I am using Voyant 2.1 on Redhat 6.   I created the ssl cert ..etc yet still get the spinning owl when I run:

java -jar Voyant.jar --headless=true
Is there a config file that I need to tweak ? Does jetty in Voyant 2.1 support ssl ?
Router is listening on 443. 

I've been trying to fix this for almost 2months...but can't seem to find out how.

**Comment by sgsinclair** [comment]
This is the fourth ticket you've opened on this issue in Voyant. As I said twice before, this is a VoyantServer issue, not for this repository https://github.com/sgsinclair/Voyant/issues/331#issuecomment-276152834

If you've gone ahead as I suggested and created an instance of Tomcat behind Apache, I can maybe be of more assistance.
