### ISSUE TITLE
Handling Segmented Tibetan 

### ISSUE THREAD

**Issue by thedirk** [sgsinclair/Voyant#342]
Like Chinese (and other unspaced languages), Tibetan requires some pre-processing before applying language analysis tools. 

Voyant currently treats each Tibetan syllable as a token: 

![screenshot 46](https://cloud.githubusercontent.com/assets/20481710/23584548/b5d2febc-019f-11e7-8cd1-6db6719329e2.png)

At issue is *this* maker: *་* U+0F0B : TIBETAN MARK INTERSYLLABIC TSHEG. In Tibetan, this interpunct occurs between each and every syllable. (we་can་i་mag་ine་if་eng་lish་were་writ་ten་like་this). For example: 

Original Text: ཆུ་ཡོད་མ་རེད། ཁང་པ་བརྗེ་བོ་བརྒྱབ་དང་ལབ་ཀྱི་འདུག་ར། ཁང་པ་བརྗེ་བོ་བརྒྱབ་ན་ང་ཚོ་འདིའི་རྒྱབ་ལོགས་འདི་ལ། ཁང་པ་ཉི་མ་ཁ་ཤས་ཤིག་ལ་མི་སླེབས་པ་ཡོད་ལབ་ཡིན་པ། 

To take full advantage of analysis tools like Voyant, we need to split not at the syllable level, but at the word level. This is what word segmentation, pre-processing is for (we can i་mag་ine if eng་lish were writ་ten like this). 

For spelling purposes, the intersyllabic tsheg is retained, and denotes multiple syllables within one word. Meanwhile, spaces separate words: 

Word Segmented Text: ཆུ ཡོད མ་རེད ། ཁང་པ བརྗེ་བོ བརྒྱབ དང ལབ ཀྱི འདུག་ར ། ཁང་པ བརྗེ་བོ བརྒྱབ་ན ང་ཚོ འདི འི རྒྱབ་ལོགས འདི ལ ། ཁང་པ ཉི་མ ཁ་ཤས ཤིག ལ མི སླེབས་པ ཡོད ལབ ཡིན་པ ། 

Even with a word-segmented text, what we see is that Voyant treats the U+0F0B marker just as a regular space or other punctuation: ie, as a word break. Thus, our word list becomes a list of single syllables: 

![screenshot 48](https://cloud.githubusercontent.com/assets/20481710/23584649/2fc679ae-01a2-11e7-83b1-075ddc802d65.png)

What we'd _like_ to see is the U+0F0B marker holding things together at the word level (here, our list includes multi-syllable words, since I've replaced the U+0F0B marker with an apostrophe): 

![screenshot 47](https://cloud.githubusercontent.com/assets/20481710/23584651/4cfd1122-01a2-11e7-85bc-e502930155e7.png)

**Comment by sgsinclair** [comment]
Thanks for the detailed issue report. I'll have a look and see if we can't figure out a good solution.

**Comment by sgsinclair** [comment]
So, just to record it, here's some more information about the current segmentation behaviour. The ICU-based Unicode word segmentation is doing some things right, apparently, but still breaking on the TSHEG when apparently it shouldn't.

* original text (4 whitespaces): ཆུ་ཡོད་མ་རེད། ཁང་པ་བརྗེ་བོ་བརྒྱབ་དང་ལབ་ཀྱི་འདུག་ར། ཁང་པ་བརྗེ་བོ་བརྒྱབ་ན་ང་ཚོ་འདིའི་རྒྱབ་ལོགས་འདི་ལ། ཁང་པ་ཉི་མ་ཁ་ཤས་ཤིག་ལ་མི་སླེབས་པ་ཡོད་ལབ་ཡིན་པ།
* current ICU tokenization (28 whitespaces: ཀྱི ཁ ཁང ང ཆུ ཉི དང ན པ བརྒྱབ བརྗེ བོ མ མི ཚོ འདི འདིའི འདུག ཡིན ཡོད ར རེད རྒྱབ ལ ལབ ལོགས ཤས ཤིག སླེབས
* manual segmentation (32 whitespaces): ཆུ ཡོད མ་རེད ། ཁང་པ བརྗེ་བོ བརྒྱབ དང ལབ ཀྱི འདུག་ར ། ཁང་པ བརྗེ་བོ བརྒྱབ་ན ང་ཚོ འདི འི རྒྱབ་ལོགས འདི ལ ། ཁང་པ ཉི་མ ཁ་ཤས ཤིག ལ མི སླེབས་པ ཡོད ལབ ཡིན་པ །

Creating a script-based word breakiterator hasn't seemed to help, possibly because "bo" (Tibetan) isn't specially defined, though it could help to create a manual break definition file. Before that I'll see if I can override the break iterator to check for the TSHEG character and force it to be a letter when it's mid-word.

**Comment by thedirk** [comment]
Yes, it looks like your ICU tokenization does indeed remove all punctuation (including the TSHEG), which results in syllables only. 

Just as a quick note, "right" and "wrong", in this situation, would depend on your set of assumptions... Word-breaking isn't the norm yet for Tibetan, so it could certainly be argued that the system is doing everything "right." If you included the TSHEG character by default, and users feed the system un-segmented data, it would recognize full phrase and sentence-level data as tokens (then you're arguably worse off than if you have the syllable data). 

Still, I think it's a good idea to start this kind of thing, and to keep pushing and prodding Tibetan NLP in the right direction. Word-level data is the goal, and neither syllable nor sentence breaking will get us there. Our assumptions for NLP tools (as is the standard / norm for other un-spaced languages) ought to include word-breaking as the standard pre-processing necessity (of course, at least until tools come bundled with automatic word segmentation for Tibetan :p ). 

Thanks for looking into this for us!

**Comment by sgsinclair** [comment]
Ok, so I dove deeper than expected into the dark bowels of ICU-based Unicode word segmentation rules, and I think I've made some progress. The word tokens don't quite match what you have, but at least the mid-word TSHEG character seems to usually stay with the word. For ease of reading, Iput these in columns:

* original text (4 whitespaces): ཆུ་ཡོད་མ་རེད། ཁང་པ་བརྗེ་བོ་བརྒྱབ་དང་ལབ་ཀྱི་འདུག་ར། ཁང་པ་བརྗེ་བོ་བརྒྱབ་ན་ང་ཚོ་འདིའི་རྒྱབ་ལོགས་འདི་ལ། ཁང་པ་ཉི་མ་ཁ་ཤས་ཤིག་ལ་མི་སླེབས་པ་ཡོད་ལབ་ཡིན་པ།

<table><tr><th>manual</th><th>Current Voyant</th><th>Tsheg-Aware Voyant</th></tr><tr><td valign="top">ཆུ<br/>
ཡོད<br/>
མ་རེད<br/>
།<br/>
ཁང་པ<br/>
བརྗེ་བོ<br/>
བརྒྱབ<br/>
དང<br/>
ལབ<br/>
ཀྱི<br/>
འདུག་ར<br/>
།<br/>
ཁང་པ<br/>
བརྗེ་བོ<br/>
བརྒྱབ་ན<br/>
ང་ཚོ<br/>
འདི<br/>
འི<br/>
རྒྱབ་ལོགས<br/>
འདི<br/>
ལ<br/>
།<br/>
ཁང་པ<br/>
ཉི་མ<br/>
ཁ་ཤས<br/>
ཤིག<br/>
ལ<br/>
མི<br/>
སླེབས་པ<br/>
ཡོད<br/>
ལབ<br/>
ཡིན་པ<br/>
།</td><td valign="top">ུ<br/>
ཡོད<br/>
མ<br/>
རེད<br/>
ཁང<br/>
པ<br/>
བརྗེ<br/>
བོ<br/>
བརྒྱབ<br/>
དང<br/>
ལབ<br/>
ཀྱི<br/>
འདུག<br/>
ར<br/>
ཁང<br/>
པ<br/>
བརྗེ<br/>
བོ<br/>
བརྒྱབ<br/>
ན<br/>
ང<br/>
ཚོ<br/>
འདིའི<br/>
རྒྱབ<br/>
ལོགས<br/>
འདི<br/>
ལ<br/>
ཁང<br/>
པ<br/>
ཉི<br/>
མ<br/>
ཁ<br/>
ཤས<br/>
ཤིག<br/>
ལ<br/>
མི<br/>
སླེབས<br/>
པ<br/>
ཡོད<br/>
ལབ<br/>
ཡིན<br/>
པ</td><td valign="top">ཆུ<br/>
ཡོད་མ་རེད<br/>
ཁང་པ་བརྗེ<br/>
བོ<br/>
བརྒྱབ་དང་ལབ་ཀྱི<br/>
འདུག་ར<br/>
ཁང་པ་བརྗེ<br/>
བོ<br/>
བརྒྱབ་ན་ང་ཚོ<br/>
འདིའི<br/>
རྒྱབ་ལོགས་འདི<br/>
ལ<br/>
ཁང་པ་ཉི<br/>
མ་ཁ་ཤས་ཤིག་ལ་མི<br/>
སླེབས་པ་ཡོད་ལབ་ཡིན་པ</td></tr></table>

Some of the tsheg-aware word tokens are pretty long (right-most column), I guess the question for you is whether those tokens are more useful than the middle ones. I'm not sure what else I could do to try to get closer to the manual tokenization, short of having someone submit a patch with a better Lucene Analyzer for Tibetan :).

**Comment by thedirk** [comment]
and what happens if you feed the TSHEG-aware Voyant the already tokenized text? :) 

we have a word segmenter, it's not manually done... so "submit a patch with a better Lucene Analyzer for Tibetan" is something we could look into...

**Comment by sgsinclair** [comment]
So the new tsheg-aware tokenizer should now be in place and used by default (when a text contains that character).

As for a pre-tokenized text, your best bet is to use the whitespace tokenizer which does as it says (but beware that it doesn't any strip punctuation, so your pre-tokenized text should take care of that too, if desirable). More information here: http://voyant-tools.org/docs/#!/guide/corpuscreator-section-tokenization

Please re-open the ticket if need be for tsheg, or open a new one if there's a separate issue.
