### ISSUE TITLE
reader apparently not working properly as tool

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#381]
For some reason:

* works: http://voyant-tools.org/?corpus=austen&view=Reader
* not so much: http://voyant-tools.org/tool/Reader/?corpus=austen

possibly relevant: https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/app/panel/Reader.js#L804

**Comment by ajmacdonald** [comment]
For some reason the same ext element ID is being used twice, which is why the canvas is getting targeted.

**Comment by ajmacdonald** [comment]
Could be related to this https://www.sencha.com/forum/showthread.php?334508-ExtJS-6-2-0-Errors-in-Ext-dom-Element-getViewportScale-amp-getViewportTouchScale

**Comment by ajmacdonald** [comment]
Appears to be resolved.
