### ISSUE TITLE
Add default stopwords for Greek and Latin

### ISSUE THREAD

**Issue by aurelberra** [sgsinclair/Voyant#382]
It would be really helpful to add default lists of stopwords in Voyant for Ancient Greek and Latin. A good reference, derived from the Perseus Project data, is the aptly-named [Stopwords for Greek and Latin](http://wiki.digitalclassicist.org/Stopwords_for_Greek_and_Latin) page on the Digital Classicist wiki. I updated the page last year (to add missing articles and take into account all breathings and accents, as well as both forms of sigma and of the apostrophe as encountered in digital sources). The attached lists could be used. Would it take anything else to implement this?

I don't know if the auto-detect function can work for those languages.

If I can be of any help to test, please let me know!

[stopwords_grec.txt](https://github.com/sgsinclair/Voyant/files/1363365/stopwords_grec.txt)
[stopwords_latin.txt](https://github.com/sgsinclair/Voyant/files/1363364/stopwords_latin.txt)

**Comment by pbinkley** [comment]
Should probably add 'siue', 'vel' and 'vero' to the Latin list, to avoid making assumptions about normalized orthography (unless Voyant normalizes as well).

**Comment by aurelberra** [comment]
Good point! I have given less thought to the Latin list, but u/v and i/j alternatives should be included indeed…

**Comment by pbinkley** [comment]
:+1:

**Comment by aurelberra** [comment]
This update will definitely benefit from the excellent work done by @diyclassics on NLP standards for [stopwords](https://github.com/diyclassics/stopwords) creation (for the Latin modules of the [Classical Language Toolkit](https://github.com/cltk/cltk)).

I am comparing the lists. However, Voyant Tools users will no doubt use widely different corpora (periods, genres, etc.), so the default stoplists ought to be short and consensual, in my opinion.

**Comment by aurelberra** [comment]
I have prepared a quick [summary of the comparison between current DigiClass and CLTK lists](https://github.com/aurelberra/stopwords/blob/master/elements_for_discussion.md) (the R code used for the analysis is in the same repo). This is only a basis for discussion and there are important pending decisions, e.g. including categories that can be meaningful in many contexts (like demonstratives or the verb "esse").

**Comment by aurelberra** [comment]
I have updated the Latin data and added the Greek counterpart. Please see the [overview](https://github.com/aurelberra/stopwords/blob/master/elements_for_discussion.md).

The suggested lists are still open for testing and comments, but could be implemented, @sgsinclair.
https://github.com/aurelberra/stopwords/blob/master/stopwords_latin.txt
https://github.com/aurelberra/stopwords/blob/master/stopwords_greek.txt

**Comment by sgsinclair** [comment]
Thanks so much @aurelberra and @pbinkley! 

https://github.com/sgsinclair/Voyant/commit/1ada5d20bd74021ab758d9709062dd801450c154
https://github.com/sgsinclair/trombone/commit/8f4f1b726aec40fe33be80bbf8fb26b9833a86a8

**Comment by aurelberra** [comment]
I have prepared thoroughly [revised versions of the lists for Ancient Greek and Latin](https://github.com/aurelberra/stopwords), which could replace the current ones. I am much happier with the results of my tests.

I explain the revision steps in the [rationale](https://github.com/aurelberra/stopwords/blob/master/rationale.md) and give details in the [revision notes](https://github.com/aurelberra/stopwords/blob/master/revision_notes.md).

I think the lists are now sounder, as they are based on a statistical analysis of the usual digital libraries. However, since Voyant Tools understandably doesn't allow for lemmatisation (inflected forms of the variable words) and automatic inclusion of alternative forms (changing accents, forms of the sigma, contraction, dialectal variants), this also means the number of items has been considerably augmented.

Here are a few questions:

* Does the length of the lists matter in any way? From my tests on the online and server versions of Voyant Tools, I don't think it is the case.
* It seems that the stoplists, whether loaded from the default files or user-defined, are used as alphabetically-sorted lists of unique values, where lines starting with a `#` are removed. Could you confirm that there is a deduplication and that comments can (sparsely) be used in the files?
* I saw this comment in the modern Greek stoplist (`stop.el.greek-lucene.txt`) derived from the "Lucene Greek Stopwords list": "Note: by default this file is used after GreekLowerCaseFilter, so when modifying this file use 'σ' instead of 'ς'". I don't suppose such pre-processing is implemented in Voyant Tools, but I feel I should ask, because the final sigma variants account for more than 2000 items in my revised version.

Comments are most welcome on any aspect of the update!

**Comment by sgsinclair** [comment]
Thanks so much Aurélien! https://github.com/sgsinclair/trombone/commit/d5fbda23444d86f8fe5caa961549db6b1eb775a9

To answer your questions:

* the length of the list shouldn't really impact performance (especially not at the scale we're discussing)
* correct that [leading hash symbols indicate comments](https://github.com/sgsinclair/trombone/blob/master/src/main/java/org/voyanttools/trombone/model/Keywords.java#L167) and that lookup is based on a [hash set](https://github.com/sgsinclair/trombone/blob/master/src/main/java/org/voyanttools/trombone/model/Keywords.java#L72) (unique values; they're shown alphabetically in the Voyant UI dialog box but order doesn't matter functionally)
* we can always add special handling for any language, but at the moment the [generic lowercase filter is used for lexical forms](https://github.com/sgsinclair/trombone/blob/master/src/main/java/org/voyanttools/trombone/lucene/analysis/LexicalAnalyzer.java#L125), please let me now if we should revisit this

**Comment by aurelberra** [comment]
Then, everything seems to be fine!

I see a possible improvement, or simplification: Lucene has a specific [GreekLowerCaseFilter](https://github.com/apache/lucene-solr/blob/a3a0e0b11e4538ccdff998c09b1145ce9036ac33/lucene/analysis/common/src/java/org/apache/lucene/analysis/el/GreekLowerCaseFilter.java) for Modern Greek which "standardizes final sigma to sigma" [from here in the code](https://github.com/apache/lucene-solr/blob/a3a0e0b11e4538ccdff998c09b1145ce9036ac33/lucene/analysis/common/src/java/org/apache/lucene/analysis/el/GreekLowerCaseFilter.java#L58). Implementing the replacement of `U+03C2` (small final sigma) and `U+03F2` (lunate sigma) with `U+03C3` (small sigma) in the analyzer would allow to make the stoplist 25% thinner. (The other modifications in the Lucene `el` filter should not be used with Ancient `grc`.) So, I think it would be worthwhile to separate `grc` from the general case in the analyzer. Are there reasons not to do it?

**Comment by aurelberra** [comment]
On a related note, looking at the code I also realise that it might be easy to solve the irritating Unicode problem with acute accents in polytonic Greek (see the [last paragraph here](https://github.com/aurelberra/stopwords/blob/master/rationale.md#about-these-lists-of-ancient-greek-and-latin-stopwords)): all *oxia* accents could become combining *tonos* accents without the users having to test their source files (or find a bug the hard way after some time). For the stoplist and my tests, I had to use the [`utf8_normalize`](https://rdrr.io/cran/utf8/man/utf8_normalize.html) function in the R `utf8` package. Could normalising (to NFC) *during the import process* in Voyant Tools be an option?

**Comment by sgsinclair** [comment]
I don't think the size of the grc list matters at the Voyant end, but we could use the GreekLowerCaseFilter if it makes the stoplist more rational to maintain. Just to be sure I understand, it would be best to pass both Greek and Ancient Greek through the GreekLowerCaseFilter (but no other parts of the analysis pipeline would differ from the current processing)?

Normalizing Greek to NFC is an option, but do we risk corrupting characters without knowing the source encoding/normalization?

For unit testing, could you please create very short examples of Greek and Ancient Greek texts and provide the anticipated lowercase token counts?

**Comment by aurelberra** [comment]
In the Lucene `GreekLowerCaseFilter` I was actually only interested in the normalisation of variants forms of `sigma` [in the analyser](https://github.com/apache/lucene-solr/blob/a3a0e0b11e4538ccdff998c09b1145ce9036ac33/lucene/analysis/common/src/java/org/apache/lucene/analysis/el/GreekLowerCaseFilter.java#L58). This could be extended to include lunate sigmas in addition to final sigmas in a new `AncientGreekLowerCaseFilter`:

|                                          | From |  To  |
|------------------------------------------|------|------|
| Small final sigma (ς) to small sigma (σ) | 03C2 | 03C3 |
| Lunate sigma (ϲ) to small sigma (σ)      | 03F2 | 03C3 |

Normalising sigmas can be useful to deal with heterogeneous corpora, as the distinction is never meaningful. But if we take this into account in the stoplists, that's fine.

How relevant this replacement (and others as the ones in the Lucene code) can be depends on which tools and functions use the output of the analyser. It may be worthwhile to use the full Modern Greek Lucene analyser or to go the same way for Ancient Greek, adding all the relevant characters in order to normalise to the base forms, without breathings or accents, but I am not fully aware of the implications, as I don't know how this aspect of Voyant Tools works.

Normalising all text to NFC Unicode during text import may be incautious. Precombined diacritics concern the text as it is displayed and queried. I have summed up the problem in my [revision notes](https://github.com/aurelberra/stopwords/blob/master/revision_notes.md#precombined-diacritics). It boils down to implementing the following replacements:

|                                       | Duplicate Form (*oxia*) |     | Use (*tonos*) |     |
| ---------------------------           | :----------------:      | --- | :------:      | --- |
| Lowercase Alpha + acute               | 1F71                    | ά   | 03AC          | ά   |
| Uppercase Alpha + acute               | 1FBB                    | Ά   | 0386          | Ά   |
| Lowercase Epsilon + acute             | 1F73                    | έ   | 03AD          | έ   |
| Uppercase Epsilon + acute             | 1FC9                    | Έ   | 0388          | Έ   |
| Lowercase Eta + acute                 | 1F75                    | ή   | 03AE          | ή   |
| Uppercase Eta + acute                 | 1FCB                    | Ή   | 0389          | Ή   |
| Lowercase Iota + acute                | 1F77                    | ί   | 03AF          | ί   |
| Uppercase Iota + acute                | 1FDB                    | Ί   | 038A          | Ί   |
| Lowercase Omicron + acute             | 1F79                    | ό   | 03CC          | ό   |
| Uppercase Omicron + acute             | 1FF9                    | Ό   | 038C          | Ό   |
| Lowercase Upsilon + acute             | 1F7B                    | ύ   | 03CD          | ύ   |
| Uppercase Upsilon + acute             | 1FEB                    | Ύ   | 038E          | Ύ   |
| Lowercase Omega + acute               | 1F7D                    | ώ   | 03CE          | ώ   |
| Uppercase Omega + acute               | 1FFB                    | Ώ   | 038F          | Ώ   |
| Lowercase Iota + dialytika + acute    | 1FD3                    | ΐ   | 0390          | ΐ   |
| Lowercase Upsilon + dialytika + acute | 1FE3                    | ΰ   | 03B0          | ΰ   |

In any case, the rest of the analysis would indeed remain unchanged.

I have included test files in my `voyant_test_files` directory: for [Ancient Greek with oxia](https://github.com/aurelberra/stopwords/blob/master/voyant_test_files/voyant_test_grc_oxia.txt) and [Ancient Greek with tonos (NFC)](https://github.com/aurelberra/stopwords/blob/master/voyant_test_files/voyant_test_grc_tonos_nfc.txt) (156 words), and [Modern Greek](https://github.com/aurelberra/stopwords/blob/master/voyant_test_files/voyant_test_el.txt) (89 words). Are they helpful?

**Comment by sgsinclair** [comment]
Thanks for the test files, very useful. I've [added](https://github.com/sgsinclair/trombone/blob/65d5e1d1b136a3d880449dab06fe2322f44292c3/src/main/java/org/voyanttools/trombone/lucene/analysis/LexicalAnalyzer.java#L124) GreekLowerCaseFilter which should now kick in for all Greek texts (your test files are auto detected as "el"). I've also added [some tests](https://github.com/sgsinclair/trombone/blob/65d5e1d1b136a3d880449dab06fe2322f44292c3/src/test/java/org/voyanttools/trombone/input/index/LuceneIndexerTest.java#L142) which confirm that the GreekLowerCaseFilter behaves differently for the test texts compared to the generic lowercase filter.

This doesn't yet address any active normalization (though it confirms that the oxio and tonos look the same to Voyant) and it still requires the user to select the Ancient Greek stoplist from the UI post corpus-creation. I'm working on adding UI elements to select language pre ingestion and then I'll confirm that the right list is loaded by default by Voyant.

Let me know if you want to keep exploring normalization.

**Comment by aurelberra** [comment]
Is there a way for me to test the new behaviour? I see that the code on the dev repo and I haven't tried to use Trombone on its own yet.

**Comment by sgsinclair** [comment]
I just deployed a new preview build at the hosted URL https://voyant-tools.org

**Comment by aurelberra** [comment]
Is the analyser used when the text is imported, once and for all, and not only as a pre-processing for specific tools? I was asking which tools use the output of the filter, because GreekLowerCaseFilter is not suitable for Ancient Greek as it is: the code for "small final sigma (ς) to small sigma (σ)" is useful for counts, but results in mangled (let's say, bad looking) Greek in, e.g., Cirrus. The final sigma should be kept and should still be the form read everywhere, but behind the scenes it should be treated as a small sigma. I thought the idea was to define a very simple AncientGreekLowerCaseFilter (possibly adding the lunate sigma to the code, but removing the normalisation to base forms in GreekLowerCaseFilter). Do you think this is feasible? If it's too complicated, Voyant Tools' previous behaviour, with the new stoplists, is preferable.

On the other hand, the other normalisation proposals would indeed happen during the import.

Let me know if this is too much work!

**Comment by sgsinclair** [comment]
Yes, the analyzer is used only during ingestion, which determines the lexical forms that are indexed (one might expect the same analyzer to be used for the query, as is the case with most search engines, but that causes its own problems when the goal is counting terms and not just finding documents). The indexed forms can be somewhat filtered by tools post-ingestion (using stopword lists or user-provided queries like [ςσ]).

I'm not sure I understanding why ς and σ should be counted as the same but should be rendered differently. I'm also curious about why the transcoding would result in mangled output in Cirrus, could this be a separate font issue? Is there any reason to suspect we may have the same problem with the larger normalization table you provided, or should it be safe to implement (I'm happy to try it as long as it seems worthwhile)?

**Comment by sgsinclair** [comment]
BTW, I'm a bit surprised by this, is it possible that the oxia and tonos files are the same, that they've somehow been normalized en route?

> $ git clone https://github.com/aurelberra/stopwords.git
> Cloning into 'stopwords'...
> remote: Counting objects: 755, done.
> remote: Compressing objects: 100% (78/78), done.
> remote: Total 755 (delta 51), reused 65 (delta 29), pack-reused 648
> Receiving objects: 100% (755/755), 11.07 MiB | 12.81 MiB/s, done.
> Resolving deltas: 100% (404/404), done.
> $ cd stopwords/voyant_test_files/
> $ diff  voyant_test_grc_oxia.txt  voyant_test_voyant_test_grc_tonos_nfc.txt

No differences? Is ```diff``` normalizing?

**Comment by aurelberra** [comment]
I checked and found out that I had normalised the oxia sample file at some point (I see that the text displayed by GitHub in Firefox is also normalised, but you did test the files from the cloned repo). I restored it to the version I used for my tests. I do get the expected `diff`, where only vowels with an acute accent differ. Sorry for the mishap!

![screen shot 2018-01-18 at 21 39 48](https://user-images.githubusercontent.com/1230441/35120365-2c494710-fc98-11e7-9883-f50952010c24.png)

**Comment by aurelberra** [comment]
After reading your questions I gave more thought to the case of sigmas. *Mangled* is probably not the term I should have used, as the word is displayed normally in Cirrus, but with the non final sigma (σ) instead of the usual final sigma (ς). A word like ὄρθρος will always be spelt this way in our printed editions, dictionaries and databases, with a final sigma. So, this is the form I expect to see in the reader widget, in the wordcloud, and in all the other tools. In other words, when I see ὄρθροσ, my eyes bleed. However, σ and ς are just allographs: it is a progress to have the forms counted together by default and displayed as only one form in the widgets. If that normalised form could be the one ending with ς, it would in fact be great. Can you alter the filter to normalise σ to ς in final position (σ to ς if it is followed by anything else than an alphabetic character, I guess) and keep σ in every non final position?

The same reasoning goes for the third allograph, the lunate sigma (ϲ), which is the form found for all sigmas in certain editions (hence the a priori surprising fact that two articles ending in ϲ are in the TLG 1000 MFW, τῆϲ and τοῖϲ). All forms of ὄρθροϲ should be displayed and counted as ὄρθρος. But in this case the filter should normalise ϲ to ς in final position and ϲ to σ in every other, non final position.

Does it make sense to you? I'm trying to justify the decision, so that others can also see the rationale later if we go this way.

**Comment by aurelberra** [comment]
Finally, I can't see how the *oxia* to *tonos* normalisation could create problems, but I now realise my proposal is pointless: as far as I can tell, the text is already normalised during the import in Voyant Tools, since I find the vowels with *tonos* in all tools and export windows when I load my test file containing vowels with *oxia*. That seems settled.

**Comment by sgsinclair** [comment]
No worries about the normalization mixup.

I've deployed a new version that uses a [new Greek filter](https://github.com/sgsinclair/trombone/blob/d4e7c31856812be6f62d310901ea26eb8f2441e1/src/main/java/org/voyanttools/trombone/lucene/analysis/el/GreekCustomFilter.java) – if you could have a quick skim, that would be great, especially around [here](https://github.com/sgsinclair/trombone/blob/d4e7c31856812be6f62d310901ea26eb8f2441e1/src/main/java/org/voyanttools/trombone/lucene/analysis/el/GreekCustomFilter.java#L43) (where all those sigmas are treated the same based on their position in the word).

**Comment by aurelberra** [comment]
It looks perfect to me, both in the code and in the tools! Many thanks @sgsinclair for this glorious, if somewhat niche, update.

I will remove the redundant forms and submit the lighter Greek stoplist as soon as possible.

**Comment by sgsinclair** [comment]
Thanks to you for working on it with me! It may be niche, but I'm happy to have examples of how Voyant is a reflection of its users.

Closing the ticket for now, though of course other things may come up.

**Comment by aurelberra** [comment]
Here is the revised list for Greek, without the now redundant variant forms of sigma: [stopwords_greek_v2_1.txt](https://github.com/aurelberra/stopwords/blob/master/stopwords_greek_v2_1.txt).

**Comment by sgsinclair** [comment]
Thanks, new list in place.

I realized I was transcoding the oxia to tonos but not lowercasing (silly logical oversight), so there's now a new version with [fixed code](https://github.com/sgsinclair/trombone/blob/42e0c88450e688869799cf9cfb847eef1c2b84fc/src/main/java/org/voyanttools/trombone/lucene/analysis/el/GreekCustomFilter.java).

**Comment by aurelberra** [comment]
Excellent. I had checked the codepoints but missed the logic of the Java `switch`, as I saw a `toLowerCase` method in the end…

*Merci pour tout*!
