### ISSUE TITLE
Cirrus doesn't seem to obey categories if it redoes its layout

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#389]
This seems fine at first: http://voyant-tools.org/?corpus=7fa142b302872ef43bfb7b80f0ee9462&view=Cirrus&stopList=stop.en.taporware.txt&categories=b812d6e33667791f1279d276ebaa64eb&whiteList=keywords-804bfc996311aff320587fd19d089174&visible=115

but if you resize the window, the category orientations seem lost.

**Comment by sgsinclair** [comment]
Then again, maybe the categories aren't being obeyed initially either…

**Comment by ajmacdonald** [comment]
Category features weren't being loaded unless you went into the Builder and re-saved. This is fixed now.
