### ISSUE TITLE
DToC: Hide from the reading area the content of the <RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> tag

### ISSUE THREAD

**Issue by ilovan** [sgsinclair/Voyant#399]
Context: this is the tag added by CWRC-Writer to all documents processed with CWRC-Writer - be they TEI, CWRC or Orlando schema documents. It contains all the rdf annotations that CWRC_Writer adds to the documents when users tag and link  named entities.

The DToC stylesheet should hide this element and its contents from the text area. 
Ideally also, the element should not  show up in the tags tab either.

**Comment by sgsinclair** [comment]
Can you please provide a link to a sample document?

**Comment by ilovan** [comment]
- Orlando Biography: https://github.com/cwrc/CWRC-Writer-Templates/commit/5dcc19881b87896c0f5f54a2968cc81f639bd5e0#diff-fed36e93a0509e20f2dc96cbbd85b678
- Orlando Writing: https://github.com/cwrc/CWRC-Writer-Templates/commit/12a3f16c1a31206212eb04ab09c0cba05c4eb0fc#diff-fed36e93a0509e20f2dc96cbbd85b678
- CWRC Schema: https://github.com/cwrc/CWRC-Writer-Templates/commit/953ea60b100cf8f49eafb6516bc46675ac3024f0#diff-fed36e93a0509e20f2dc96cbbd85b678
- CWRC TEI lite: https://github.com/ilovan/T.S.-Eliot---Old-Possum-s-Book-of-Practical-Cats-first-three-poems-/blob/master/document.xml

**Comment by ajmacdonald** [comment]
fixed by https://github.com/sgsinclair/Voyant/commit/8b649faaef7f434a66aacd60497ca9a8c7ef9fb4
