### ISSUE TITLE
DToC Curator mode: reordering chapters not working

### ISSUE THREAD

**Issue by ilovan** [sgsinclair/Voyant#424]
Noticed in: http://voyant-tools.org/dtoc/?corpus=fb2ae3a6ef79c06e3ed42fc585c2a0f4&docId=26d9f4e36e3abc5d7c1bd3f03e5700aa&curatorId=1518363009029.9955

According to Susan, rearranging chapters should be available in curator mode. This means manually rearranging the chapter titles in the ToC and having the content in the text area rearrange itself automatically to mirror the new order in the ToC. 

The included link contains a rearranged ToC, but the content  failed to mirror the new ToC.

**Comment by ajmacdonald** [comment]
I think I see what's happening. @ilovan do you recall if you did multiple curations? i.e. loaded up a curation, curated it, then loaded the new curation?

**Comment by ajmacdonald** [comment]
Should be fixed by https://github.com/sgsinclair/Voyant/commit/3300d48de08bc21c1bd03835b36f9a799d16b614
