### ISSUE TITLE
stopword case sensitive

### ISSUE THREAD

**Issue by coast77777777777** [sgsinclair/Voyant#455]
In current state, each stopword requires conversion to lowercase to operate.
I am requesting option to handle each stopword without regarding upper and lower case letters.

**Comment by sgsinclair** [comment]
Although the current stopword list operates on a lowercase representation of the documents I think it would be best to not cut-off the possibility of maintaining case significance. One possibility would be to add some tools to the dialog box, such as "convert stopwords to lowercase" – what do you think?

**Comment by coast77777777777** [comment]
Because I have experienced multiple first time users repeat this mistake of not using all lowercase, I think the default system behavior should nudge users past that barrier. In other words, case insensitive by default. Please explain when/how I can leverage case sensitive stop words?

**Comment by sgsinclair** [comment]
The current lexical search doesn't allow you to leverage case, but the system is designed to eventually support other types of search (like all words starting with a capital letter). You're right that the current editor is limited to the lowercase functionality, so maybe forcing lowercase automatically makes sense. A bigger issue that people have is with apostrophes that take various forms.

**Comment by sgsinclair** [comment]
lowercase of stopword list editor is In version control (but not yet deployed): c93e5df762f706c2b8f8ebe9c163efad5985bdb8
