### ISSUE TITLE
Feature request: GoWord

### ISSUE THREAD

**Issue by ghost** [sgsinclair/Voyant#456]
I am requesting the option to inject/modify data in voyant tools.
My intention is for concept mapping because my peers and myself have identified the gap here.
Please enable option to add "document terms" unrelated to corpus.
Please consider addition of 'GoWord' to facilitate brainstorming outwardly with teams.

**Comment by sgsinclair** [comment]
The easiest way to inject new words is to use the Documents tool to add a new document and type/paste the new words in that box, resulting in a new corpus.

I'm not sure I understand what you mean by a GoWord, could you please elaborate?

**Comment by coast77777777777** [comment]
It was my shabby attempt at naming a class/object (inverse of stopword). Imagine the GUI with a few Text input boxes:
<img width="960" alt="Untitled-1" src="https://user-images.githubusercontent.com/7040493/68148197-7c7f0b00-ff09-11e9-884d-abcb9e1d5958.png">

**Comment by sgsinclair** [comment]
Thanks for the sketch, that's very helpful. But why on earth would you add an arbitrary word to the corpus? Do you really mean a word that's not already in the documents or that's not already in the list? You can use the checkboxes to keep selected words visible.
