### ISSUE TITLE
Feature Request: Concatenate significant patterns of Juxtaposed document terms as new 'Compound Document term'

### ISSUE THREAD

**Issue by ghost** [sgsinclair/Voyant#457]
For example, I am performing analysis of engineering education venues because I think there might be an undervaluation of theory-driven investigation of writing processes within the engineering education community. My Voyant use case scenario considers the Journal of Engineering Education, the International Journal of Engineering Education, the European Journal of Engineering Education and in the Cambridge Handbook of Engineering Education Research as important venues for publication within this field.  I would like to see the collocates of "Engineering Education" as a compound document term

**Comment by sgsinclair** [comment]
Are you referring to a phrase search? Placing the search terms in double quotes should achieve that. The collocates will be of single words, there's currently no way to request n-gram collocates directly.

**Comment by coast77777777777** [comment]
I will test it out explore. What do you mean by n-gram collocates?

**Comment by sgsinclair** [comment]
I mean that you can search for phrases like "engineering education" and find single word collocates for that phrase, but not other recurring phrases that are also collocates.
