### ISSUE TITLE
Bubblelines error when clicking on a bubble

### ISSUE THREAD

**Issue by susanmonnelly** [sgsinclair/Voyant#462]
Steps to recreate:

- Start here: https://voyant-tools.org/tool/Bubblelines/?corpus=austen
- Click on a bubble, opens a new window in the 5 panel default display
- See the Trends and Contexts panels are empty 
- open the browser console and see ISEs 
- URL created for new window is this: https://voyant-tools.org/?corpus=austen&query=[object%20Object]&query=[object%20Object]&query=[object%20Object]&query=[object%20Object]&query=[object%20Object]

![Screen Shot 2020-01-16 at 4 16 09 PM](https://user-images.githubusercontent.com/12297503/72563404-975feb00-387b-11ea-9e4a-5b3931f84bcf.png)

**Comment by sgsinclair** [comment]
Thanks, keep the bug reports coming!
