### ISSUE TITLE
content not copyable for export bibliographic reference

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#466]

**Comment by sgsinclair** [comment]
@ajmacdonald could you please have a quick look at this in case I'm missing something obvious. Notice my (failed) efforts at https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/app/util/Toolable.js#L596

**Comment by ajmacdonald** [comment]
This fixes it: https://github.com/sgsinclair/Voyant/commit/1569e4b5a09643f9881454a96b6d0b969d47e8b7

What you were trying seems like it should've worked, but I think the issue was that the `x-unselectable` class that the dialog parent has does more than just set the `user-select` properties.

**Comment by sgsinclair** [comment]
Thanks, that was too easy for you :) Since you're on a role, any interest in confirming and fixing #470?
