### ISSUE TITLE
expand row in grid not working in Chrome

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#470]
This seems to be a problem in Chrome on Mac (not sure about Windows), but not in Safari. My guess is that Chrome made a change that broke something (i.e. I don't think we introduced a new but), but I could be wrong. Sometimes things are different between buffered and non-buffered grids, but I'd hate to go back to non-buffered grids.

**Comment by ajmacdonald** [comment]
Here's a fix: df038be6abd97f632bc9eed6c12bddf5f874ad54
Although it's now closed, this could be the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=897373

innerText had a tab character in it, so the check wasn't working properly. This was occurring in Firefox too.

**Comment by sgsinclair** [comment]
@ajmacdonald === "hero" && thanks()
