### ISSUE TITLE
Failed attempt to create a corpus

### ISSUE THREAD

**Issue by Annette461** [sgsinclair/Voyant#481]
Hello, a very new user of Voyant here. I've been trying to create a corpus using a text file (61KB) but am getting the following error message (see screenshot attached). I'm using Voyant on my own computer but get the same "failed attempt to create a corpus" when I try on the web also. I'm not a programmer so would appreciate some insight in non-programming terms that I can hopefully use. Thanks in advance...
![1 Screenshot 2020-05-05 at 13 10 28](https://user-images.githubusercontent.com/64847832/81072163-a37cc080-8edd-11ea-907b-e0c76316bde0.png)

**Comment by sgsinclair** [comment]
There's a server-settings.txt file in the distribution directory, open that in a text editor and modify the line that says memory. Judging by your error I'd suggest double it to 2048, but other settings are possible depending on your system's RAM.
