### ISSUE TITLE
Spyral.Load.file needs to honour new file when file name clicked and dialog has chosen different file

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#486]

**Comment by ajmacdonald** [comment]
I'm not sure how this would work since you can only choose a file once (because of the promise based setup).

You need to remove and re-add the file input in order to choose a different file.

**Comment by sgsinclair** [comment]
It looks like it would be tricky to do a double-check of the filename. Maybe we could add a click listener and warn the user that if they want to change the file, they'll need to remove the existing one first. Then again, I wonder if we need to keep the file input there after processing; we could remove the snippet that's been added and just use our own label. I suspect the browser is careful with the file upload capabilities though, so who know's what's possible.

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/voyantjs/commit/542eccc9e143c40d7401085e290363559b6e712e
