### ISSUE TITLE
cancel Spyral.Load.files()

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#489]
running Spyral.Load.files() produces a spinning wheel and a (overly subtle) link to Choose a file or drag and drop, but there doesn't seem to be a good way of cancelling out of there. Could the working spinner be accompanied somewhere in close proximity to some mechanism to cancel? It may not be possible (and it may be very rarely needed), but still.

I note that even pressing the close x doesn't hide the spinning wheel.

**Comment by ajmacdonald** [comment]
The close button now rejects the promise, which removes the spinning wheel.

https://github.com/sgsinclair/voyantjs/commit/f04a7095b3d650496e1a36d27d1ce3b07ae2d837
