### ISSUE TITLE
experiment with more/less for data code cells (editor, saved, printed)

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#492]

**Comment by sgsinclair** [comment]
It would be nice for results that are one line to only take one line. More generally, if the results is smaller than the default size it should shrink to that size.

**Comment by sgsinclair** [comment]
The sizes would be respected when exporting (and printing). We need to ensure that it works full circle as well: download notebook (with results sizes) and import (with the same result sizes)

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/Voyant/commit/29d2b2f9f3a74caf0d195dd4c8927d925145b8ba
