### ISSUE TITLE
loadCorpus should accept array of texts as first argument

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#496]
There's been a regression bug since this used to work:

loadCorpus(["text one","text two"]);

And of course additional arguments should work too:

loadCorpus(["text one","text two"], {inputRemoveUntilAfter: "text"});

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/voyantjs/commit/980f5ab20dcd216dd6de5aec91eda2f5699d5b39

**Comment by sgsinclair** [comment]
Thanks, but when I try this I get 1 document and I should get two (sorry I wasn't clear about this). In other words each text in the array is a document, they don't get concatenated:

loadCorpus(["one and two","three and four"]); // should produce 2 documents

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/voyantjs/commit/3973e643a785c506e132b096c58e3f8dfb77f5d0
