### ISSUE TITLE
Visually indicate when there are more results that are collapsed

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/Voyant#500]
experiment with various possibilities:

* repeat expand button
* show an ellipsis
* show a squiggly line

**Comment by sgsinclair** [comment]
<img width="477" alt="Screen Shot 2020-07-06 at 11 33 44 AM" src="https://user-images.githubusercontent.com/355388/86611485-b747b000-bf7c-11ea-8acf-94fd49e6257d.png">

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/Voyant/commit/c29e7a8fbb5cb4281d1d7fbd5e0447c2ce13e3a0
