### ISSUE TITLE
Exporting as PNG with Scaling > 1.0 offsets graph to top left outside of image

### ISSUE THREAD

**Issue by Robyt3** [sgsinclair/Voyant#504]
Tried with Cirrus and StreamGraph. With Scaling = 3 the exported image is totally blank because the graph is completely outside the image.

Exporting as SVG works as a workaround.

I'm using Firefox on Windows 10.

**Comment by ajmacdonald** [comment]
Thanks for finding this.

**Comment by ajmacdonald** [comment]
9fccb6132f959c15e0c47927000b2dab14085f3f
