### ISSUE TITLE
delete tool 

### ISSUE THREAD

**Issue by chiaramine** [sgsinclair/Voyant#511]
i am using your project for my university thesis, i need to know how to delete a tool from the menu.
For exemple i need to delete dremscape from the toolbar. how can I do?
Thank you.
Chiara

**Comment by ajmacdonald** [comment]
Hello Chiara,
Can you please explain your issue further? Which menu are you referring to? If it is this one, then unfortunately the menu cannot be customized (unless you are working with your own local copy of Voyant).

![Screenshot 2020-10-29 122842](https://user-images.githubusercontent.com/882444/97603144-7f102580-19e2-11eb-83ad-af82833f5526.png)

**Comment by chiaramine** [comment]
Hello,
in my web application I import the voyant.war file into my web server, I would like to know if there is a way to remove dreamscape from the corpus tool. I downloaded the Voyant project, I would like to modify it and create a new .war file with the changes in the menu. however I can't find a way to modify the corpus tool. can you please indicate the code that I had to change?
Thank you so much.
Chiara

**Comment by ajmacdonald** [comment]
The entries for that menu are populated here: https://github.com/sgsinclair/Voyant/blob/master/src/main/webapp/app/VoyantCorpusApp.js#L25-L47
You'd need to remove the dreamscape entries from `moreToolsScaleCorpus` and `moreToolsTypeViz`.

**Comment by chiaramine** [comment]
Hello,
I made the changes you told me and created a new .war file but nothing has changed. Do you know of another way to modify the 'corpus tool' menu?Do you know what the problem could be?
Chiara

**Comment by ajmacdonald** [comment]
I'm not sure why it's not working for you, unfortunately. When I make those changes locally it removes dreamscape. However, I'm not building the .war file, so it may be related to that. If you make some other arbitrary changes, do they persist in the .war file?
