### ISSUE TITLE
Internal HTML links don't work on Spyral Notebooks

### ISSUE THREAD

**Issue by kaylinland** [sgsinclair/Voyant#513]
Issue linking to different parts of same Spyral Notebook page with HTML header tags. A hyperlink is created and the URL changes to reflect the link but user is not directed to different part of the page.

**Comment by ajmacdonald** [comment]
I was able to get this working but it wasn't straightforward. The main issue seems to be that the underlying text editor replaces empty anchors with an image (note to self: [possibly related](https://dev.ckeditor.com/ticket/3582)).

The workaround is to select a range of text before adding the anchor. This prevents the behaviour that causes the anchor to replaced with an image.

**Comment by kaylinland** [comment]
I think understand what you're saying, but it's still not working for me. The page I'm working on is this one: https://voyant-tools.org/spyral/startALTA

Before I had: 
[in the top cell]
`<li><a data-tabindex-counter="10" data-tabindex-value="none" href="#metadata" id="ext-element-22" tabindex="-1" target="_self">metadata</a></li>`

[lower in the document in another cell]
`<h2><a name="metadata"></a>Metadata</h2>`

To select a range of text before adding the anchor I've tried the following, none of which redirect me to the correct place in the document. The url updates with the anchor extension (`#metadata`), but stays at the top of the page. 

1. `<h2><a name="metadata">Metadata</a></h2>`
2. `<h2>Metadata<a name="metadata"></a></h2>`
3. `<h2><a name="metadata">Meta</a>data</h2>`
4. `<h2>Metadata</h2> <p> Some text about <a name="metadata"></a> metadata. </p>`

Thanks!

**Comment by ajmacdonald** [comment]
I tried to record the process I took to achieve it, hopefully you can tell what I'm doing.

![Spyral-Google-Chrome-2020-11-11](https://user-images.githubusercontent.com/882444/98863123-e774f300-2435-11eb-929d-0d001d8d6c70.gif)

**Comment by kaylinland** [comment]
Yes, I can! Thanks so much--I understand what you were saying now. Very helpful!

**Comment by ajmacdonald** [comment]
Glad to hear. I will close the issue now.
