### ISSUE TITLE
Re-format a text file

### ISSUE THREAD

**Issue by wilcar** [sgsinclair/Voyant#515]
Hello, I have a corpus of 50 newspapers articles ordered by dates and saved in a single text file. I would like to be able to compare them by newspapers and dates. Is it possible to format my text file so that I can compare the different newspapers ?
Thank you in advance.

**Comment by ajmacdonald** [comment]
If you convert the file to XML then you can use XPath selectors to split it into documents, which you can then compare with each other. See here for more info: https://voyant-tools.org/docs/#!/guide/corpuscreator-section-xml
