### ISSUE TITLE
How to save Categories

### ISSUE THREAD

**Issue by Hjaek** [sgsinclair/Voyant#525]
Hello everyone,

i have Voyant running on a local server and would like to save the categories i added in the session.
Right now it seems to overwrite it with every reboot of the tool, is there a way to save these categories?

Kind regards

**Comment by ajmacdonald** [comment]
Hi @Hjaek,

After modifying the categories and clicking on the Save button, you will be able to see the categories ID:
![image](https://user-images.githubusercontent.com/882444/109529537-d521d200-7a83-11eb-8e8b-e85935b6aef2.png)

You can then add this to the query parameters in the URL to load those categories, e.g. https://voyant-tools.org/?corpus=austen&categories=41a2237d9277778fe5facca19721612e

You can also get an URL by using the Export button for the tool where you edited the categories:
![image](https://user-images.githubusercontent.com/882444/109530152-68f39e00-7a84-11eb-8831-775588577c07.png)

I hope this helps,
Andrew
