### ISSUE TITLE
Browser window title improvements for Spyral

### ISSUE THREAD

**Issue by ajmacdonald** [sgsinclair/Voyant#526]
- [ ] use a blue variant of the Voyant Owl as Spyral favicon
- [ ] display notebook title in browser window title

**Comment by kaylinland** [comment]
Very excited to see the blue owl appear this morning!

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/Voyant/commit/a437345d8f02f0ed7a4da4c8f6ab741a4e1bb66b

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/Voyant/commit/1b76c73065155fb4d4e1107744b69eef463238e9
