### ISSUE TITLE
Spyral In-Page Hyperlinks Stop Functioning After Clicking in Cell

### ISSUE THREAD

**Issue by kaylinland** [sgsinclair/Voyant#529]
Hyperlinks (from one text cell to another in Spyral Notebooks) only work when you first load the page. After you've loaded the page and clicked in a text cell, the hyperlinks no longer work until you re-load the page.

**Comment by ajmacdonald** [comment]
Looks like it's intentional, perhaps for security reasons.
https://stackoverflow.com/questions/45551431/ckeditor-make-links-clickable-when-in-read-only-mode

I'm going to see if I can find a workaround.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/11bcf842787f4d459f277e338feb0c5c3c556cb8
