### ISSUE TITLE
Voyant Server needs space? 

### ISSUE THREAD

**Issue by nashra94** [sgsinclair/Voyant#530]
Hello all, 

I am attempting to create a corpus via Voyant Tools but keep getting the error "no space left". Does this mean the Voyant server has run out of space? Is anyone else encountering this issue? Any recommendations on how to get around it? 

Appreciate any help! 
Thanks

**Comment by ajmacdonald** [comment]
Hello!
Thank you for bringing this to our attention. The server did indeed run out of space. I've cleaned it up a bit so you should now be able to create a new corpus.

**Comment by nashra94** [comment]
Thank you SO MUCH! I really appreciate it.
