### ISSUE TITLE
hebrew stop words

### ISSUE THREAD

**Issue by sarnov** [sgsinclair/Voyant#532]
Hi,

I would like to add a hebrew stop words list.  Can you tell how to contribute such a list? any guidelines for such list?

Thanks.

**Comment by ajmacdonald** [comment]
Hello @sarnov 
Thank you for your interest in contributing!

The current list of stop words is here: https://github.com/sgsinclair/trombone/tree/master/src/main/resources/org/voyanttools/trombone/keywords

As you can see, each list is a simple text file with new lines separating each word.

If you are familiar with GitHub, you can submit your list using the pull request feature. See here for more info: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
